import { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card/Card'
import styles from '../styles/Home.module.css'

const API = 'https://upcodes-frontend-challenge.herokuapp.com/v0/get-illustrations'

export default function Home() {
  const [filter, setFilter] = useState('');
  const [data, setData] = useState([]);

  useEffect(() => {
    fetch(API).then((res) => res.json()).then(({ illustrations }) => setData(illustrations))
  }, [])


  let previewData = data


  if (filter) {
    previewData = previewData.filter(({ codeType }) => (codeType as string).toLowerCase() === filter)
  }

  const handleChange = (e: React.ChangeEvent<any>) => {
    setFilter(e.currentTarget.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{padding: '4rem'}}>
        <h1>Illustrations</h1>
        <div>
          <select onChange={handleChange}>
            <option>{''}</option>
            <option>accessibility</option>
            <option>concrete</option>
            <option>electrical</option>
          </select>
        </div>
        <div className={styles.grid}>
          {previewData.map(({ title, codeType }) => (<Card type={(codeType as string).toLowerCase()} title={title}/>))}
        </div>

      </main>
    </div>
  )
}
